included:
  - Sources
  - Tests
disabled_rules:
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - large_tuple
  - nesting
  - trailing_comma
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - redundant_nil_coalescing
